# Place here the bot token that can be get from https://discordapp.com/developers/applications/me
bot-token: "REPLACEBOTTOKEN"
# Place here the discord server id of the server you want the role to be given in.
server-id: "REPLACESERVERID"

# Place here the discord role IDs of the roles that you want to give players
roles:
  - Donor: "REPLACEROLEID"
  - Iron: "REPLACEROLEID"

# Place here the prefix you want the plugin to use. No need to add a space at the end.
prefix: "&6[&r&eDonorRole&6]&2"

# Time till verify request times out when no one answers. Put -1 if you want no timeout. IN MINUTES
verifyTimeout: 2
